### ISSUE TITLE
`d` vs. `F_M` in the Bresenham's circle writeup

### ISSUE THREAD

**Issue by akavel** [listx/listx_blog#3]
Hi! In the super cool article about the Bresenham's circle algorithm, I believe you start mixing `d` and `F_M` from about the `get_circle_points_bresenham_WIP2` definition. In particular, in `get_circle_points_bresenham_WIP2`, there's some use of a `d` variable that seems not defined elsewhere in the code, and the accompanying text above and below the func seems to mix `d` and `F_M`. Or was `d` introduced somewhere and I just missed it?

Also, there seems to be some INSERT LINK still lingering out there ;)

Thanks for publishing, by the way, was great to read!

**Comment by listx** [comment]
Thank you so much!

Let me have a look and try to address all of your points, and update you here when I think I've addressed them all.

**Comment by listx** [comment]
Doh, I forgot that GitHub auto-closes commits if you reference issue numbers. Anyway I think 7e0d07223bd5fed6d1d5583afaf5df1f26c41afa should fix your concerns. Please let me know if there is anything else "off" about the article, I really appreciate it.

**Comment by akavel** [comment]
There's still quite a few "d" occurences further down below, I'd recommend searching for `\bd\b` or something like that; though maybe the `$d$ ($F(M)$)` fragment is kinda acceptable, though I believe it'd be easier to read if it stayed consistent; for a non-mathematician like me, the article is already dense enough without accidental complexity ;) with all that said, I think I started getting lost somewhere around the *Second-order differences*, so can't say much more about that part. As to other unrelated things, I'd say it was not clear to me at some point why there was `F(x+1,...)` vs. `F(x+2,...)`, instead of just `F(x,...)` vs. `F(x+1,...)` - if you could add a bit of elaboration about that, might be helpful! Sorry for throwing all those things into this one issue :/ I guess it's easiest for me to be using it as a kinda comment section of the blog...

**Comment by listx** [comment]
Thanks, I think I fixed those last occurrences of `d` vs `F(M)`.

> Second-order differences, so can't say much more about that part

It would help me if you can be a bit more specific about what is unclear, so I can try to fix/reword what I can.

>  F(x+1,...) vs. F(x+2,...), instead of just F(x,...) vs. F(x+1,...) - if you could add a bit of elaboration about that, might be helpful!

I'll have another look at these parts and get back to you on this thread.

> Sorry for throwing all those things into this one issue

Not at all --- I sincerely apprecate the feedback!

> I guess it's easiest for me to be using it as a kinda comment section of the blog...

I opted against having a comment section a long time ago because (1) spam bots and (2) I simply don't have the time to moderate them. I think this issue tracker is a reasonable alternative.

**Comment by listx** [comment]
I've done some more rewording with 665a8f5.
